### ISSUE TITLE
Hiba a !parancsok-kal

### ISSUE THREAD

**Issue by FMate01** [Adam1236126/SmileBot#6]
Ha valaki beírja a !parancsok parancsot és ki van kapcsolva a privát üzenetek fogadása, a bot sikert ír, pedig nem küld üzenetet.
Javaslat: Ha privátban nem tudja elküldeni, mert discord.Forbidden kivételt dob, küldje be a parancs kiadásának csatornájába(a parancs argumentumban kapott discord.ext.commands.Context objektumának send() metódusával).

**Comment by Adam1236126** [comment]
Köszönjük a bejelentésedet, megkapod a szerveren a Bug Hunter rangot!
![51ir9NIB26L](https://user-images.githubusercontent.com/66472233/101488127-7acf1480-395f-11eb-9a0e-bad2d49619b1.jpg)
